//-------------------------------------------------------------------------------------------------
//
//  File : lib_class_modbus.cpp
//
//-------------------------------------------------------------------------------------------------
//
// Copyright(c) 2026 Alain Royer.
// Email: aroyer.qc@gmail.com
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software
// and associated documentation files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
// AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//-------------------------------------------------------------------------------------------------

//-------------------------------------------------------------------------------------------------
// Include file(s)
//-------------------------------------------------------------------------------------------------

#include "./lib_digini.h"

//-------------------------------------------------------------------------------------------------

#if (DIGINI_USE_MODBUS == DEF_ENABLED)

//-------------------------------------------------------------------------------------------------
//
//  Name:           BuildFrame
//
//  Parameters:     Command     - Parsed Modbus command to serialize
//                  pOut        - Output buffer where the Modbus frame will be written
//                  MaxLength   - Maximum number of bytes available in the output buffer
//
//  Returns:        > 0         - Total frame length written to pOut
//                  0           - Frame could not be built (invalid payload or insufficient space)
//
//  Description:    Serializes a Modbus command into a complete RTU frame. The function writes
//                  the UnitID, Function code, payload generated by BuildPayload(), and finally
//                  appends the Modbus CRC16. If the payload cannot be generated or the output
//                  buffer is too small, the function returns 0 to indicate failure.
//
//-------------------------------------------------------------------------------------------------
int MODBUS_Manager::BuildFrame(const MODBUS_Command_t& Command, uint8_t* pOut, size_t MaxLength)
{
    size_t Index = 0;
    
    pOut[Index++] = Command.UnitID;                                             // Address (UnitId)
    pOut[Index++] = Command.Function;                                           // Function
    int PayloadLength = BuildPayload(Command, &pOut[Index], MaxLength - Index); // Payload according to function

    if(PayloadLength < 0)
    {
        return 0;
    }

    Index += PayloadLength;

    if((Index + 2) > MaxLength)                                                 // CRC
    {
        return 0;
    }
    
    CRC_Driver ModbusCRC;
    ModbusCRC.Initialize(CRC_16_MODBUS);
    uint16_t CRC_Result = uint16_t(ModbusCRC.CalculateBuffer(pOut, Index));
    pOut[Index++] = (uint8_t)(CRC_Result & 0xFF);                               // CRC Low
    pOut[Index++] = (uint8_t)((CRC_Result >> 8) & 0xFF);                        // CRC High

    return (int)Index;
}

//-------------------------------------------------------------------------------------------------
//
//  Name:           ParseResponse
//
//  Parameters:     Command     - Original Modbus command that this response corresponds to
//                  pIn         - Pointer to the received Modbus RTU frame
//                  Length      - Total number of bytes in the received frame
//
//  Returns:        >= 0        - Payload successfully parsed; value is function-specific status
//                  < 0         - Modbus exception code (negative value)
//                  -1          - Invalid frame (CRC, UnitID, function mismatch, or format error)
//
//  Description:    Validates and interprets a received Modbus RTU response. The function checks
//                  minimal frame length, UnitID, CRC integrity, and function code. If the frame
//                  indicates a Modbus exception (function | 0x80), the exception code is returned
//                  as a negative value. Otherwise, the payload is delegated to ParsePayload() for
//                  function-specific extraction.
//
//-------------------------------------------------------------------------------------------------
int MODBUS_Manager::ParseResponse(const MODBUS_Command_t& Command, const uint8_t* pIn, size_t Length)
{
    if(Length < 4)                                              // Minimal length
    {
        return -1;
    }

    size_t  Index    = 0;
    uint8_t UnitID   = pIn[Index++];
    uint8_t Function = pIn[Index++];

    if(UnitID != Command.UnitID)                                // Verify UnitID
    {
        return -1;
    }

    if(ValidateCRC(pIn, Length) == false)                       // Verify CRC
    {
        return -1;
    }

    if(Function & 0x80)                                         // MODBUS Exception ?
    {
        uint8_t ExceptionCode = pIn[Index];
        return -ExceptionCode;                                  // Standard : negative error
    }

    if(Function != Command.Function)                            // Verify function
    {
        return -1;
    }

    int Status = ParsePayload(Command, Function, &pIn[Index], Length - Index);      // Extract payload according to function

    return Status;
}

//-------------------------------------------------------------------------------------------------
//
//  Name:           ValidateCRC
//
//  Parameters:     pData       - Pointer to the received Modbus RTU frame
//                  Length      - Total number of bytes in the frame, including CRC
//
//  Returns:        true        - CRC is valid and matches the computed Modbus CRC16
//                  false       - Frame too short or CRC mismatch
//
//  Description:    Extracts the CRC16 value appended to the end of a Modbus RTU frame and
//                  recomputes the CRC over all preceding bytes. The function compares the
//                  received CRC with the computed one and returns true only if they match.
//
//-------------------------------------------------------------------------------------------------
bool MODBUS_Manager::ValidateCRC(const uint8_t* pData, size_t Length)
{
    if(Length < 3)
    {
        return false;
    }

    uint16_t ReceivedCRC = (uint16_t)pData[Length - 2] | ((uint16_t)pData[Length - 1] << 8);
    CRC_Driver ModbusCRC;
    ModbusCRC.Initialize(CRC_16_MODBUS);
    uint16_t ComputedCRC = (uint16_t)ModbusCRC.CalculateBuffer(pData, Length - 2);
    return (ReceivedCRC == ComputedCRC);
}

//-------------------------------------------------------------------------------------------------
//
//  Name:           ParsePayload
//
//  Parameters:     Command     - Original Modbus command containing buffers for parsed results
//                  Function    - Function code extracted from the response frame
//                  pIn         - Pointer to the payload of the response (after UnitID/Function)
//                  Length      - Number of bytes available in the payload buffer
//
//  Returns:        0           - Payload successfully parsed
//                  -1          - Invalid or incomplete payload format
//                  < 0         - Reserved for exception codes (handled earlier in ParseResponse)
//
//  Description:    Interprets the function-specific payload of a Modbus RTU response. The function
//                  validates the payload length according to the expected format of the specified
//                  function code and extracts coil states or register values into the buffers
//                  provided in the Command structure. For write-type functions, the response is an
//                  echo of the request and requires no data extraction.
//
//-------------------------------------------------------------------------------------------------
int MODBUS_Manager::ParsePayload(const MODBUS_Command_t& Command, uint8_t Function, const uint8_t* pIn, size_t Length)
{
    switch(Function)
    {
        case MODBUS_READ_COILS:
        case MODBUS_READ_DISCRETE_INPUTS:
        {
            if(Length < 1)
            {
                return -1;
            }

            uint8_t ByteCount = pIn[0];

            if(Length < (size_t)(1 + ByteCount))
            {
                return -1;
            }

            // Copy data in Command.ResultBuffer
            memcpy(Command.ResultBuffer, &pIn[1], ByteCount);
            Command.ResultLength = ByteCount;
            return 0;
        }

        case MODBUS_READ_HOLDING_REGISTERS:
        case MODBUS_READ_INPUT_REGISTERS:
        {
            if(Length < 1)
            {
                return -1;
            }

            uint8_t ByteCount = pIn[0];

            if(Length < (size_t)(1 + ByteCount))
            {
                return -1;
            }

            // Register per register extraction
            for(size_t i = 0; i < (ByteCount / 2); i++)
            {
                uint16_t Value = ((uint16_t)pIn[1 + (i * 2)] << 8) | (uint16_t)pIn[2 + (i * 2)];
                Command.Data[i] = Value;
            }

            Command.ResultLength = ByteCount / 2;
            return 0;
        }

        // Write Single Coil / Register
        case MODBUS_WRITE_SINGLE_COIL:
        case MODBUS_WRITE_SINGLE_REGISTER:
        {
            if(Length < 4)
            {
                return -1;
            }

            // Echo command -> nothing to extract
            return 0;
        }

        case MODBUS_WRITE_MULTIPLE_REGISTERS:
        {
            if(Length < 4)
            {
                return -1;
            }

            // Echo address + quantity -> OK
            return 0;
        }
    }

    return -1;
}

//-------------------------------------------------------------------------------------------------


//-------------------------------------------------------------------------------------------------

//-------------------------------------------------------------------------------------------------
//
//  Name:           MODBUS_Router (constructor)
//
//  Parameters:     None
//
//  Description:    Initializes the router by clearing the backend table. All backend slots are
//                  set to nullptr, indicating that no Modbus backends are registered yet. Backends
//                  will be attached later through explicit registration calls.
//
//-------------------------------------------------------------------------------------------------
MODBUS_Router::MODBUS_Router()
{
    for(size_t BackEnd = 0; BackEnd < MODBUS_MAX_BACKENDS; BackEnd++)
    {
        m_BackEnds[BackEnd] = nullptr;
    }
}

//-------------------------------------------------------------------------------------------------
//
//  Name:           Process
//
//  Parameters:     None
//
//  Returns:        Nothing
//
//  Description:    Iterates through all registered Modbus backends and invokes their Process()
//                  method. Each backend is responsible for handling its own state machine,
//                  timeouts, and queued Modbus operations. Backends that are not registered
//                  (nullptr entries) are skipped.
//
//-------------------------------------------------------------------------------------------------
void MODBUS_Router::Process(void)
{
    for(size_t BackEnd = 0; BackEnd < MODBUS_MAX_BACKENDS; BackEnd++)
    {
        if(m_BackEnds[BackEnd] != nullptr)
        {
            m_BackEnds[BackEnd]->Process();
        }
    }
}

//-------------------------------------------------------------------------------------------------
//
//  Name:           RegisterEndpoint
//
//  Parameters:     pBackEnd    - Pointer to a Modbus backend implementing IModbusBackend
//
//  Returns:        true        - Backend successfully registered in the first available slot
//                  false       - No free slot available; backend table is full
//
//  Description:    Registers a Modbus backend with the router. The backend is stored in the
//                  first empty slot of the internal backend table. Once registered, the backend
//                  will be included in the router's periodic Process() calls.
//
//-------------------------------------------------------------------------------------------------
bool MODBUS_Router::RegisterEndpoint(IModbusBackend* pBackEnd)
{
    for(size_t BackEnd = 0; BackEnd < MODBUS_MAX_BACKENDS; BackEnd++)
    {
        if(m_BackEnds[BackEnd] == nullptr)
        {
            m_BackEnds[BackEnd] = pBackEnd;
            return true;
        }
    }
    
    return false; // No more space
}

//-------------------------------------------------------------------------------------------------
//
//  Name:           Queue
//
//  Parameters:     Command     - Modbus command to route toward the appropriate backend
//
//  Returns:        true        - Command successfully queued to a backend
//                  false       - No backend available to handle the command or passthru target
//
//  Description:    Routes a Modbus command to the correct backend. The router first checks
//                  passthru rules: if the command's UnitID matches a passthru source, the
//                  UnitID is rewritten to the mapped destination and the command is forwarded
//                  to the backend capable of handling that destination address. If no passthru
//                  rule applies, the router searches for a backend that can handle the original
//                  UnitID. If no backend matches, the command cannot be queued.
//
//-------------------------------------------------------------------------------------------------
bool MODBUS_Router::Queue(const MODBUS_Command_t& Command)
{
    // Check passthru rules if it exist
    for(size_t Rules = 0; Rules < MODBUS_MAX_RULES; Rules++)
    {
        if(Command.UnitID == m_PassthruRules[Rules].SrcUnitID)
        {
            ModbusCommand_t NewCommand = Command;
            NewCommand.UnitID = m_PassthruRules[Rules].DstUnitID;

            // Find backend for new UnitID
            for(size_t BackEnd = 0; BackEnd < MODBUS_MAX_BACKENDS; BackEnd++)
            {
                MODBUS_InterfaceBackEnd* pBackEnd = m_BackEnds[BackEnd];

                if((pBackEnd != 0) && (pBackEnd->CanHandle(NewCommand.UnitID) == true))
                {
                    return pBackEnd->Queue(NewCommand);
                }
            }

            return false;
        }
    }

    for(size_t BackEnd = 0; BackEnd < MODBUS_MAX_BACKENDS; BackEnd++)
    {
        MODBUS_InterfaceBackEnd* pBackEnd = m_BackEnds[BackEnd];

        if((pBackEnd != nullptr) && (pBackEnd->CanHandle(Command.UnitID) == true))
        {
            return pBackEnd->Queue(Command);
        }
    }

    return false; // No backend to handle this address
}

//-------------------------------------------------------------------------------------------------
//
//  Name:           IsBusy
//
//  Parameters:     None
//
//  Returns:        true        - At least one registered backend reports it is busy
//                  false       - All registered backends are idle or no backends are registered
//
//  Description:    Scans all registered Modbus backends and queries their busy state. This allows
//                  higher-level logic to determine whether any backend is currently processing a
//                  transaction, waiting on a timeout, or handling queued operations. Backends that
//                  are not registered (nullptr entries) are ignored.
//
//-------------------------------------------------------------------------------------------------
bool MODBUS_Router::IsBusy(void)
{
    for(size_t BackEnd = 0; BackEnd < MODBUS_MAX_BACKENDS; BackEnd++)
    {
        if((m_BackEnds[BackEnd] != nullptr) && (m_BackEnds[BackEnd]->IsBusy() == true))
        {
            return true;
        }
    }
    
    return false;
}

//-------------------------------------------------------------------------------------------------
//  Name:           Queue
//
//  Parameters:     Command     - Modbus command to route toward the appropriate backend
//
//  Returns:        true        - Command successfully queued to a backend
//                  false       - No backend available to handle the command's UnitID
//
//  Description:    Routes a Modbus command to the backend responsible for the specified UnitID.
//                  The router scans all registered backends and selects the first one whose
//                  CanHandle() method confirms ownership of the target address. If no backend
//                  accepts the UnitID, the command cannot be queued.
//-------------------------------------------------------------------------------------------------
bool MODBUS_Router::Queue(const MODBUS_Command_t& Command)
{
    for(size_t BackEnd = 0; BackEnd < MODBUS_MAX_BACKENDS; BackEnd++)
    {
        IModbusBackEnd* pBackEnd = m_BackEnds[BackEnd];

        if((pBackEnd != nullptr) && (pBackEnd->CanHandle(Command.UnitID) == true))
        {
            return pBackEnd->Queue(Command);
        }
    }

    return false;   // No backend to handle this address
}

//-------------------------------------------------------------------------------------------------

#endif // (DIGINI_USE_MODBUS == DEF_ENABLED)

//-------------------------------------------------------------------------------------------------
